title:            Scribble
description:      A jekyll theme. Because I scribble.
baseurl:          /scribble
url:              
signoff:          佳锅锅
disqus_shortname: Jiaguoguo
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:

  - name:         About
    url:          /about
  - name:         Blog
    url:          http://muan.co
    external:     true
  - name:         Email
    url:          mailto:hello@muan.co
    external:     true
  - name:         GitHub
    url:          http://github.com/muan
    external:     true

highlighter:      pygments

pygments:         true
>>>>>>> 88f64b947609b9de00bca89c6be12960158cfc01
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
