title:            佳锅锅
description:      一个很 Low 的 Ruby 程序员。但是，他们喜欢叫我 Artist.

url:              http://jiaguo.xyz
signoff:          佳锅锅
disqus_shortname: jiaguo
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         关于
    url:          /about
  - name:         Feed
    url:          /feed.xml
    external:     true
  - name:         GitHub
    url:          http://github.com/onizuka1229
    external:     true
  - name:         Twitter
    url:          https://twitter.com/oni7uka
    external:     true
  - name:         微博
    url:          http://weibo.com/oni7uka
    external:     true

highlighter:      pygments

pygments:         true

permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
